event/urls.py
from django.urls import re_path,path
from .views import *


#url for app
urlpatterns = [
    path('<int:id>/<str:event_title>/', view_event),
    path('join_event', join_event, name = 'join_event'),
    path('', event_func, name = 'event_page'),
    path('check_user_is_registered', check_user_is_registered, name='check_user_is_registered')
]

registerMemberApp/urls.py
from django.conf.urls import url
from .views import index, saveMember, registerSuccess

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^registerSuccess', registerSuccess, name='registerSuccess'),
    url(r'^saveMember', saveMember, name='saveMember'),
]

studentunion/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.conf.urls import include,url
from registerEvent.views import register
from aboutApp.views import about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('newsApp.urls'), name = "news_page"),
    path('registerMember/', include(('registerMemberApp.urls', 'register_member'), namespace='register_member')),
    path('register/', include(('registerEvent.urls', 'register' ), namespace='register')),
    path('profile/',include(('profileApp.urls','profile'),namespace='profile')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('', include('event.urls'), name="event_page"),
    path('about/', include(('aboutApp.urls', 'about'), namespace='about'), name="about"),
    # re_path('',include('mainApp.urls')),

]

registerMemberApp/models.py
from django.db import models

class memberModel(models.Model):
    firstName = models.CharField(max_length = 20, verbose_name='')
    lastName = models.CharField(max_length = 20, verbose_name='')
    birth = models.DateField(verbose_name='')
    email = models.EmailField(unique = True, verbose_name='', 
    	error_messages={'unique':"This email has already been registered."})
    address = models.CharField(max_length = 30, verbose_name='')
    username = models.CharField(max_length = 15, unique = True, verbose_name='', 
    	error_messages={'unique':"This username has already been registered."})
    password = models.CharField(max_length = 20, verbose_name='')

registerMemberApp/forms.py
from django import forms
from .models import memberModel
import datetime

class registerMemberForm(forms.ModelForm):
    class Meta:
        model = memberModel
        fields = '__all__'
        fields_required = '__all__'
        widgets = {
            'firstName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "First Name"}),
            'lastName': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Last Name"}),
            'birth': forms.DateInput(attrs={'type': 'text', 'onfocus': "(this.type = 'date')", 'class': 'form-control', 'placeholder': "Date of Birth"}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "Email"}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Home Address"}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Username"}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': "Password"}),
        }

    passwordAgain = forms.CharField(label = '', widget = forms.PasswordInput(attrs={'class': 'form-control', 
        'placeholder': "Password (Again)"}))

    def clean(self):
        cleaned_data = super(registerMemberForm, self).clean()
        birth = cleaned_data.get('birth')
        password = cleaned_data.get('password')
        passwordAgain = cleaned_data.get('passwordAgain')
        if (datetime.datetime.now().date() < birth):
            self.add_error('birth', "Date of birth can't be in the future!")
        if (len(password) < 8):
            self.add_error('password', "Password must be at least 8 characters long")
        elif (password.isalnum() == False):
            self.add_error('password', "Password must only contains letters or numbers")
        elif (password != passwordAgain):
            self.add_error('password', "The two password fields don't match!")
        return cleaned_data

registerMemberApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import memberModel
from .forms import registerMemberForm

response = {}
def index(request):
    members = memberModel.objects.all()
    response['members'] = members
    response['form'] = registerMemberForm
    return render(request, 'register_member.html', response)

def registerSuccess(request):
    return render(request, 'register_success.html', response)

def saveMember(request):
    form = registerMemberForm(request.POST or None)
    if (request.method == "POST" and form.is_valid()):
        response['firstName'] = request.POST['firstName']
        response['lastName'] = request.POST['lastName']
        response['birth'] = request.POST['birth']
        response['email'] = request.POST['email']
        response['address'] = request.POST['address']
        response['username'] = request.POST['username']
        response['password'] = request.POST['password']
        response['passwordAgain'] = request.POST['passwordAgain']
        member = memberModel(firstName = response['firstName'], lastName = response['lastName'],
            birth = response['birth'], email = response['email'], address = response['address'], 
            username = response['username'], password = response['password'])
        member.save()
        return HttpResponseRedirect('/registerMember/registerSuccess/')
    else: 
       return render(request, 'register_member.html', {'form':form})

registerMemberApp/templates/register_member.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="title" id="regMember-title">
        <p class="regMember-p">REGISTER MEMBER</p>
        <div class="line" id="regMember-line"></div>
    </div>
    <div class="regMember-form">
        <div class="form-group">
            <form id="form" method="POST" action="{% url 'register_member:saveMember' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col" id="regMember-col1"> {{ form.firstName }}</div>
                    <div class="col" id="regMember-col2"> {{ form.lastName }} </div>
                </div>
                <div class="fieldWrapper">
                    {% if form.birth.errors %}
                        <p class="regMember-error">{{ form.birth.errors.as_text }}</p>
                    {% endif %}
                    {{ form.birth }}
                    {% if form.email.errors %}
                        <p class="regMember-error">{{ form.email.errors.as_text }}</p>
                    {% endif %}
                    {{ form.email }}
                    {{ form.address }}
                    {% if form.username.errors %}
                        <p class="regMember-error">{{ form.username.errors.as_text }}</p>
                    {% endif %}
                    {{ form.username }}
                    {% if form.password.errors %}
                        <p class="regMember-error">{{ form.password.errors.as_text }}</p>
                    {% endif %}
                    {{ form.password }}
                    {{ form.passwordAgain }}
                </div>
                <button type="submit" class="btn btn-danger-2">Register</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

registerMemberApp/templates/register_success.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="title" id="regSuccess-title">
        <p class="regSuccess-p">Thank you for registering!</p>
        <div class="line" id="regSuccess-line"></div>
    </div>
    <div class="regSuccess-email">
        <p class="regSuccess-email-p">Please check your email and click the activation link to finish your registration</p>
    </div>
</div>

{% endblock content %}