event/urls.py
from django.urls import re_path,path
from .views import *


#url for app
urlpatterns = [
    path('<int:id>/<str:event_title>/', view_event),
    path('join_event', join_event, name = 'join_event'),
    path('', event_func, name = 'event_page'),
    path('check_user_is_registered', check_user_is_registered, name='check_user_is_registered')
]

profileApp/urls.py
from django.conf.urls import url
from django.urls import re_path,path
from .views import *

app_name = 'profile'
urlpatterns = [
    path('logout/',logout,name = 'logout'),
    path('check_user', check_user, name = 'check_user'),
    path('render/', render_user_event, name='render'),
    # path('delete/', delete_join_event, name='delete'),
    path('', view_profile, name = 'profilePage'),
]

studentunion/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.conf.urls import include,url
from registerEvent.views import register
from aboutApp.views import about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('newsApp.urls'), name = "news_page"),
    path('registerMember/', include(('registerMemberApp.urls', 'register_member'), namespace='register_member')),
    path('register/', include(('registerEvent.urls', 'register' ), namespace='register')),
    path('profile/',include(('profileApp.urls','profile'),namespace='profile')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('', include('event.urls'), name="event_page"),
    path('about/', include(('aboutApp.urls', 'about'), namespace='about'), name="about"),
    # re_path('',include('mainApp.urls')),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
        Fasilkom - StudentUnion
        {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
</head>

<body>
    {% include 'nav.html' %}
    <div>
        {% block content %}
        {% endblock content %}
    </div>
    {% include 'login-modal.html' %}
    {% include 'footer.html' %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
</body>

</html>

templates/footer.html
{% load staticfiles %}

<div id="footer" class="d-flex align-items-start justify-content-between flex-wrap">
    <div id="event" class="d-flex flex-column">
        <img width="133" src="{% static 'img/icon-footer.png' %}" id="footer-icon">
        <h6><br>We create possibilities for <br> the connected events </h6>
        <h6><br><strong>keep it simple & easy!</strong></h6>
    </div>
    <div id="explore" class="d-flex justify-content-center flex-column">
        <h5><strong>EXPLORE</strong> EVENTS</h5>
        <a href="#">Recommended Events</a>
        <a href="#">Popular Events</a>
        <a href="#">Events Near You!</a>
        <br>
        <h5><strong>CONTACT</strong> US</h5>
        <div class="d-flex justify-content-start align-items-center">
            <img width=20 height=16 src="{% static 'img/mail.png' %}" id="footer-mail">
            <a href="mailto:student@union.com" id="email">student@union.com</a>
        </div>
    </div>
    <div id="stay-connected">
        <h5><strong>STAY</strong> CONNECTED</h5>
        <h6>Subscribe to our Email Mailing Listand receive the most upcoming events, information on
            ticket sales,reminders for your next events, ticket deals, news, and more. </h6>
        <br>
        <div id="email-txt" class="d-flex">
            <input id="label-email" type="email" placeholder="Enter email address">
            <input id="btn-submit" type="button" value="SUBSCRIBE">
        </div>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container-fluid">
    <div class="title" id="homePage">
        <h1>FASILKOM STUDENT UNION</h1>
        <h2>coming soon..</h2>
        <!-- Mandatory hello world -->
    </div>
</div>
{% endblock content %}  

templates/login-modal.html
{% load staticfiles %}
<div class="modal fade" id="ModalLogin" tabindex="-1" role="dialog" aria-labelledby="ModalLoginTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <img id="modal-icon" src="{% static 'img/icon-modals.png' %}" class="mx-auto d-block">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="google-btn mx-auto d-block">
        <a class="g-signin2" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">
          <img src="{% static 'img/btn_google.png' %}" width="50%" class="mx-auto d-block">
        </a>
      </div>
      <div class="ModalLogin-footer">
        <!-- ini harusnya tempat footer -->
      </div>
    </div>
  </div>
</div>

templates/nav.html
{% load staticfiles %}

<nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="{% url 'event_page' %}">

        <img src="{% static 'img/icon.png' %}" width="100" height="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'event_page' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'news_page' %}">NEWS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/about/">ABOUT US</a>
            </li>
        </ul>

        <div class="my-2 my-lg-0">
            <!-- <a class="btn btn-danger my-2 my-sm-0" href="\..\registerMember">Login</a> -->
            {% if user.is_authenticated %}
            <!-- <a href="{% url 'profile:profilePage' %}">Hello, {{ user.username }}</a> -->
            <div class="nav-item dropdown" style="text-align:center">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    {% if user.first_name %}
                    Hello, {{ user.first_name }}
                    {% else %}
                    Hello, {{user.username}}
                    {% endif %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="text-align:center">
                    <a class="dropdown-item" href="{% url 'profile:profilePage' %}">Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" style="color:#B22C2C" href="{% url 'profile:logout'%}">Logout</a>
                </div>
            </div>
            {% else %}
            <button type="button" class="btn btn-danger my-2 my-sm-0" data-toggle="modal" data-target="#ModalLogin">
                Login
            </button>
            {% endif %}
        </div>

    </div>
</nav>